name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Install goose
        run: |
          go install github.com/pressly/goose/v3/cmd/goose@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Run Build
        run: ./scripts/buildprod.sh

      - name: Authenticate with Google Cloud
        id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: Build a new Container
        run: docker build . -t andreisavelyeu/notely

      - name: Run Migrations
        run: ./scripts/migrateup.sh

      - name: Deploy to GCloud
        run: gcloud builds submit --tag us-central1-docker.pkg.dev/notely-441704/notely-ar-repo/andreisavelyeu/notely:latest

      - name: Deploy to Cloud Run
        run: gcloud run deploy notely --image us-central1-docker.pkg.dev/notely-441704/notely-ar-repo/andreisavelyeu/notely:latest --region us-central1 --allow-unauthenticated --project notely-441704 --max-instances=4
